base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('home/', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('edit/', views.edit, name="edit"),
    path('show/', views.getallstudents , name="show"),
    path('check_existing/', views.check_existing, name="check_existing"),
    path('select/<int:id>/', views.select, name="select"),
    path('search/', views.getallstudents2, name="search"),
    path('add/', views.add, name="add"),
    path('user_login/', views.user_login, name="login"),
    path('deactivate/<int:id>', views.deactivate),
    path('edit/<str:pk>/', views.edit, name="edit"),
    path('delete/<str:pk>/', views.delete, name='delete'),
    
]


djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from base import views

urlpatterns = [
    path('',  views.index , name = 'index'),
    path('base/', include('base.urls')),
    path('user_logout/', views.user_logout, name = "user_logout"),
    path('admin/', admin.site.urls),
]


base/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=50,primary_key=True)

    def __str__(self):
        return self.name


class Student(models.Model):
    stud_id = models.IntegerField(unique=True)
    stud_name = models.CharField(max_length=255)
    stud_gpa = models.DecimalField(max_digits=3, decimal_places=2)
    dateOfBirth = models.DateField()
    gender = models.CharField(max_length=7)
    status = models.BooleanField()
    level = models.CharField(max_length=1)
    email = models.EmailField(max_length=255)
    mobileNumber = models.CharField(max_length=12)
    department = models.ForeignKey(Department, models.SET_NULL,null=True)


    def __str__(self):
        return self.stud_name

    def __repr__(self):
        return self.stud_name

class UserAdmin(models.Model):
    
    user = models.OneToOneField(User, on_delete= models.CASCADE)

    def __str__(self):
        return self.user.username

base/views.py
from django.shortcuts import render, redirect
from base.models import Student, Department
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect ,csrf_exempt
from django.http import JsonResponse
from django.shortcuts import get_object_or_404



def home(requst):
    return render(requst, 'home.html')

def index(request):
    return render(request, 'index.html')


def search(request):
    return render(request, 'search.html')


def about(request):
    return render(request, 'about.html')


def show(request):
    return render(request, 'show.html')


def edit(request):
    return render(request, 'edit.html')

def deactivate(request,id):
    student = Student.objects.get(stud_id=id)
    student.status ^= True
    student.save()
    return HttpResponse("Status changed successfully!")

@login_required
@csrf_exempt
def add(request):
    if request.method == 'POST':
        # Retrieve form data
        name = request.POST.get('stud_name')
        stud_gpa = request.POST.get('stud_gpa')
        email = request.POST.get('email')
        stud_id = request.POST.get('stud_id')
        mobile_number = request.POST.get('mobile_number')
        date_of_birth = request.POST.get('date_of_birth')
        stud_gender = request.POST.get('gender')
        status = request.POST.get('status')
        stud_level = request.POST.get('level')
        department_name = request.POST.get('department')

        print(department_name, "hello world")
        # checking whether student is active
        student_status = False
        if status == "act":
            student_status = True

        # Get the Department instance based on the selected department name since its forigen key
        stud_department = Department.objects.get(name=department_name)

        # Create a new instance of the Student model
        new_student = Student(
            stud_id=stud_id,
            email=email,
            mobileNumber=mobile_number,
            stud_name=name,
            stud_gpa=stud_gpa,
            dateOfBirth=date_of_birth,
            gender=stud_gender,
            status=student_status,
            level=stud_level,
            department=stud_department
        )
        new_student.save()

    return render(request, 'add.html')


def getallstudents(request):
    Students = Student.objects.all()
    gender = "Male"
    ischecked = "checked"
    return render(request,'show.html',{'students':Students , 'gender': gender , 'ischecked':ischecked})

def getallstudents2(request):
    Students = Student.objects.all()
    gender = "Male"
    ischecked = "checked"
    return render(request,'search.html',{'students':Students , 'gender': gender , 'ischecked':ischecked})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@csrf_protect
def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                print("Login successful for Username: {}".format(username))
                return HttpResponseRedirect(reverse('base:home'))
            else:
                # Add an error message
                messages.error(request, "Invalid login credentials")
                print("account is not active for Username: {}".format(username))
        else:
            # Add an error message
            messages.error(request, "Invalid login credentials")
            print("Invalid login credentials for Username: {}".format(username))

    return render(request, 'login.html')

def page_not_found(request, exception):
    return render(request, 'ErrorPage.html', status=404)


def select(request,id):
    student = Student.objects.get(stud_id=id)
    if request.method == 'GET':
        return render(request, 'select.html',{'student':student})
    student.department = Department.objects.get(name=request.POST.get("department"))
    student.save()
    return redirect("base:search")



@csrf_exempt
def check_existing(request):
    if request.method == 'POST':
        stud_id = request.POST.get('stud_id')
        mobile_number = request.POST.get('mobile_number')
        email = request.POST.get('email')
        data = {}

        # Check if the ID exists
        if Student.objects.filter(stud_id=stud_id).exists():
            data['id_exists'] = True
        else:
            data['id_exists'] = False

        # Check if the email exists
        if Student.objects.filter(email=email).exists():
            data['email_exists'] = True
        else:
            data['email_exists'] = False

        # Check if phone number exists
        if Student.objects.filter(mobileNumber=mobile_number).exists():
            data['phone_exists'] = True
        else:
            data['phone_exists'] = False
            
        # print(JsonResponse(data))
        return JsonResponse(data)
   






@login_required
def edit(request, pk):

    if request.method == "GET":
         data = Student.objects.get(stud_id=pk)
         date = str(data.dateOfBirth)
         department = str(data.department)
         return render(request, "edit.html", {"data": data, "date": date, "dep": department})

    if request.method == "POST":
        data = Student.objects.get(stud_id = pk)
        data.stud_name = request.POST.get("name")
        data.stud_id = request.POST.get("stud_id")
        data.stud_gpa = request.POST.get("gpa")
        data.level = request.POST.get("level")
        data.dateOfBirth = request.POST.get("date")
        data.gender = request.POST.get("gender")
        data.email = request.POST.get("email")
        data.mobileNumber = request.POST.get("mobile-number")
        data.save()
        return render(request, 'home.html')

@csrf_exempt
def delete(request,pk):
    data = Student.objects.get(stud_id=pk)
    if request.method == 'POST':
        data.delete()
        return render(request, "home.html")
    return render(request, "delete.html")


templates/ErrorPage.html
<head>
  <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@600;900&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/4b9ba14b0f.js" crossorigin="anonymous"></script>

    <style>

body {
    background-image: linear-gradient(315deg, #aff6cf 0%, #9f98e8 74%);
}

.mainbox {
  margin: auto;
  height: 600px;
  width: 600px;
  position: relative;
}

  .err {
    color: #ffffff;
    font-family: 'Nunito Sans', sans-serif;
    font-size: 11rem;
    position:absolute;
    left: 20%;
    top: 8%;
  }

.far {
  position: absolute;
  font-size: 8.5rem;
  left: 42%;
  top: 15%;
  color: #ffffff;
}

 .err2 {
    color: #ffffff;
    font-family: 'Nunito Sans', sans-serif;
    font-size: 11rem;
    position:absolute;
    left: 68%;
    top: 8%;
  }

.msg {
    text-align: center;
    font-family: 'Nunito Sans', sans-serif;
    font-size: 1.6rem;
    position:absolute;
    left: 16%;
    top: 45%;
    width: 75%;
  }

a {
  text-decoration: none;
  color: white;
}

a:hover {
  text-decoration: underline;
}


    </style>

</head>
<body>
  <div class="mainbox">
    <div class="err">4</div>
    <i class="far fa-question-circle fa-spin"></i>
    <div class="err2">4</div>
    <div class="msg">Maybe this page moved? Got deleted? Is hiding out in quarantine? Never existed in the first place?<p>Let's go <a href="{% url 'base:home'%}">home</a> and try from there.</p></div>
      </div>

templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/mater.css' %}">
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>about section</title>
  </head>

    </head>
    <body>
      <header id ="header">
          {% include 'header.html' %}
      </header>

    <div class="box">
    <div class="about-section">
      <h1>About Student Affairs System</h1>
	<p>The Student Affairs System is a web-based application designed to manage student records. It provides various functionalities to add, update, delete, search, and view student records in a user-friendly interface.</p>

	<h2>Features</h2>
		<p>Add a new student to the system</p>
		<p>Update an existing student information (except department field should be shown disabled for editing)</p>
		<p>Delete an existing student data through a delete button in edit student data page with a confirmation dialogue for the action before deletion occurs</p>
		<p>Search for “active” students by name in search for students screen and students with similar names having active status should be rendered as a table</p>
		<p>Select a specific student after searching to assign a department through the student’s department assignment page. The page should include student ID, name and a dropdown list for available departments and a submit button. This action is applicable for students if level = 3 else an error should be shown to the user with a clear understandable error message</p>
		<p>View all active/inactive students in a separate page rendered in a table with a related set of attributes only</p>
		<p>Change the status of student from active to inactive or vice versa from the table viewing all students</p>
		<p>A well-designed navigation bar to go through all pages and a home page</p>

	<h2>Technologies Used</h2>
		<p>HTML</p>
		<p>CSS</p>
		<p>JavaScript</p>
        <p>Django</p>

    </div>

    <h2 style="text-align:center">Our Team</h2>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">

<section class="container">
  <div class="row">
    <div class="col-md-3 col-sm-6">
      <div class="our-team">
        <div class="pic">
          <img src="{% static 'logos/seif_img.jpg' %}">
        </div>
        <h3 class="title">Seif eldin</h3>
        <span class="post">Developer</span>
        <ul class="social">
          <li><a href="https://www.facebook.com/profile.php?id=100008623188678" class="fa fa-facebook"></a></li>
          <li><a href="#" class="fa fa-twitter"></a></li>
          <li><a href="https://www.linkedin.com/in/seif-mahmoud-48741b240/" class="fa fa-linkedin"></a></li>
        </ul>
      </div>
    </div>

    <div class="col-md-3 col-sm-6" style="margin-left: 10%;">
      <div class="our-team">
        <div class="pic">
          <img src="{% static 'logos/adhamimg.jpg' %}">
        </div>
        <h3 class="title">Adham Adel</h3>
        <span class="post">Developer</span>
        <ul class="social">
          <li><a href="https://www.facebook.com/adham.adel.547?mibextid=ZbWKwL" class="fa fa-facebook"></a></li>
          <li><a href="#" class="fa fa-twitter"></a></li>
          <li><a href="https://www.linkedin.com/in/adham-adel-a10b73232" class="fa fa-linkedin"></a></li>
        </ul>
      </div>
    </div>

    <div class="col-md-3 col-sm-6" style="margin-left: 10%;">
      <div class="our-team">
        <div class="pic">
          <img src="{% static 'logos/abdallahimg.jpg' %}">
        </div>
        <h3 class="title">Abdallah mohamed</h3>
        <span class="post">Developer</span>
        <ul class="social">
          <li><a href="#" class="fa fa-facebook"></a></li>
          <li><a href="#" class="fa fa-twitter"></a></li>
          <li><a href="#" class="fa fa-linkedin"></a></li>
        </ul>
      </div>
    </div>
    <div class="col-md-3 col-sm-6" style="margin-left: 20%;padding-top: 5%">
      <div class="our-team">
        <div class="pic">
          <img src="{% static 'logos/Tony img.jpg' %}">
        </div>
        <h3 class="title">Antonious Amgad</h3>
        <span class="post">Developer</span>
        <ul class="social">
          <li><a href="https://www.facebook.com/tony.amgadreyad?mibextid=LQQJ4d" class="fa fa-facebook"></a></li>
          <li><a href="#" class="fa fa-twitter"></a></li>
          <li><a href="https://www.linkedin.com/in/antonious-amgad-b51bb8252" class="fa fa-linkedin"></a></li>
        </ul>
      </div>
    </div>
    <div class="col-md-3 col-sm-6" style="margin-left: 10%; padding-top: 5%">
      <div class="our-team">
        <div class="pic">
          <img src="{% static 'logos/contact.jpg' %}">
        </div>
        <h3 class="title">Yasmen Amr</h3>
        <span class="post">Developer</span>
        <ul class="social">
          <li><a href="https://www.facebook.com/yasmen.amr.125?mibextid=ZbWKwL" class="fa fa-facebook"></a></li>
          <li><a href="https://twitter.com/YasmenAmr17?t=HuzWLHtr_YAUW0UaRw5c3Q&s=09" class="fa fa-twitter"></a></li>
          <li><a href="#" class="fa fa-linkedin"></a></li>
        </ul>
      </div>
    </div>

  </div>
</section>
</div>
    <dev id="footer">
      {% include 'footer.html' %}
  </dev>
    </body>
</html>

templates/add.html
<!DOCTYPE html>
{% load static %}
<!--=== Coding by CodingLab | www.codinglabweb.com === -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!----======== CSS ======== -->
	<link rel="stylesheet" href="{% static 'css/mater.css' %}" />
    <link rel="stylesheet" href="{% static 'css/add.css' %}">
    <!----===== Iconscout CSS ===== -->
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
	<!----======== SCRIPT ======== -->
	<script type="module"  defer src="{% static 'js/validation.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <title>Regisration Form</title> 
</head>
<header>
	<div id="header">
        {% include 'header.html' %}
    </div>
</header>
<body>
    <div class="container">
        <header>Add Student</header>

        <form id="form" action="/base/check_existing/" method="POST" >
            {% csrf_token %}
            <!-- =========== Personal Details =========== -->
            <div class="form-first">
                <div class="details personal">
                    <span class="title">Personal Details</span>
                    <!-- =========== FULL NAME =========== -->
                    <div class="fields">
                        <div class="input-field">
                            <label>Full Name</label>
                            <input type="text" id="name" name="stud_name" placeholder="Enter your name" required>
                            <div class="error"></div>
                        </div>

                    <!-- =========== Birth Day =========== -->
                        <div class="input-field">
                            <label>Date of Birth</label>
                            <input type="date" id="date" name="date_of_birth" placeholder="Enter birth date" required>
                            <div class="error"></div>
                        </div>

                    <!-- =========== Email =========== -->
                        <div class="input-field">
                            <label>Email</label>
                            <input type="text" id="email" name="email" placeholder="Enter your email" required>
                            <div class="error"></div>
                        </div>

                    <!-- =========== Mobile Number =========== -->
                        <div class="input-field">
                            <label>Mobile Number</label>
                            <input type="tel" id="phone" name="mobile_number" placeholder="Enter mobile number" required>
                            <div class="error"></div>
                        </div>
                        
                    <!-- =========== Status =========== -->
						<div class="input-field">
							<label>Status</label>
							<select required  id="status" name="status">
                                <option disabled selected>Select status</option>
                                <option value ="act">Active</option>
                                <option value ="inact">Inactive</option>
                            </select>
                            <div class="error"></div>
                        </div>
                    <!-- =========== Gender =========== -->
                        <div class="input-field">
                            <label>Gender</label>
                            <select required  id="gender" name="gender">
                                <option disabled selected >Select gender</option>
                                <option value = "Male">Male</option>
                                <option value = "Female">Female</option>
                            </select>
                            <div class="error"></div>
                        </div>	
                    </div>
                </div>
                    <!-- =========== Faculty Details =========== -->
                    <div class="details ID">
                        <span class="title">Faculty Details</span>
                        <div class="fields">
                    <!-- =========== ID =========== -->
                            <div class="input-field">
                                <label>ID</label>
                                <input id="id" type="text" placeholder="Enter ID type" name="stud_id" required>
                                <div class="error"></div>
                            </div>

                    <!-- =========== Department =========== -->
                            <div class="input-field">
                                <label>Department</label>
                                <select required id="department" name="department">
                                    <option disabled selected vlaue="">Select Department</option>
                                    <option value = "None">Not Yet</option>
                                    <option value = "IS">Information Systems</option>
                                    <option value = "CS">Computer Science</option>
                                    <option value = "AI">Artificial Intelligence</option>
                                    <option value = "IT">Information Technology</option>
                                    <option value = "DS">Data Science</option>
                                </select>
                                <div class="error"></div>
                            </div>

                    <!-- =========== GPA =========== -->
                            <div class="input-field">
                                <label>GPA</label>
                                <input type="number" id="gpa" min = "0.01" max ="4" step ="0.01" name="stud_gpa" placeholder="Enter GPA" required>
                                <div class="error"></div>
                            </div>

                    <!-- =========== Level =========== -->
                            <div class="input-field">
                                <label>Level</label>
                                <select id="level" required name="level">
                                    <option disabled selected>Select Level</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>
                                <div class="error"></div>
                            </div>
                        
                    <!-- =========== Password =========== -->
                            <div class="input-field">
                                <label>Password</label>
                                <input type="password" id="pass" name="password" placeholder="Enter your Password" required>
                                <div class="error"></div>
                            </div>

                    <!-- =========== Confirm Password =========== -->
                            <div class="input-field">
                                <label>Confirm Password</label>
                                <input id="confirm-pass" type="password" name="confirm-pass" placeholder="Confirm password" required>
                                <div class="error"></div>
                            </div>
                        </div>
                    <!-- =========== submit =========== -->
                        <div class = "add-button">
                        <button type="submit"  class="btnText">
                            Add
                        </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>	
    </body>
<footer id="footer">
    {% include 'footer.html' %}
</foote>	
</html>

templates/delete.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/delete.css' %}">
<!--        <link rel="stylesheet" href="{% static 'css/mater.css' %}">-->
<!--        <link rel="stylesheet" href="">-->
<!--{#        <script defer src="../static/js/main.js"></script>#}-->
<!--{#        <script defer src="../static/js/editJS.js"></script>#}-->
    </head>
    <body>
    <form method="post" action="">
        {% csrf_token %}
        <div id="myModal" class="modal fade">
          <div class="modal-dialog modal-confirm">
            <div class="modal-content">
              <div class="modal-header">
                <div class="icon-box">
                  <i class="material-icons">&#xE5CD;</i>
                </div>
                <h4 class="modal-title">Are you sure?</h4>
<!--                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>-->
              </div>
              <div class="modal-body">
                <p>Do you really want to delete these records? This process cannot be undone.</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-danger">Delete</button>
              </div>
            </div>
          </div>
        </div>
    </form>
    </body>
</html>

templates/footer.html
{% load static %}
<div class="footer-basic">
         <footer>
             <ul class="list-inline">
                 <li style="float: left;; "><img src = "{% static 'logos/universityLogo.webp' %}" id="universityLogo"></li>
                 <li style="float: left; "><img src = "{% static 'logos/facultyLogo.webp' %}" id="facultyLogo"></li>
                 {% if request.user.is_authenticated %}
                 <li class="list-inline-item"><a href="{% url 'base:home'%}">Home</a></li>
                 <li class="list-inline-item"><a href="{% url 'base:show'%}">Show all students</a></li>
                 <li class="list-inline-item"><a href="{% url 'base:search'%}">search/edit</a></li>
                 <li class="list-inline-item"><a href="{% url 'base:about'%}">About</a></li>
                 {% endif %}
             </ul>
             <p class="copyright">Copyright © 2022-2023 Faculty of Computers and Artificial Intelligence 5 Dr. Ahmed Zewail Street, Postal Code: 12613, Orman, Giza, Egypt.</p>
         </footer>
</div>

templates/header.html
<head>
{#      <script defer src="../static/js/main.js"></script>#}
</head>
<div>
  <ul>
    <li style="float: left;padding: 10px;" id="facultyName"><label>F C A I</label></li>
    <ul>
    {% if not request.user.is_authenticated %}
        <li><a href="{% url 'base:login'%}">Login</a></li>
    {% endif %}
        <li><a href="{% url 'base:about'%}">About</a></li>
        {% if request.user.is_authenticated %}
      <li> <a class="navbar-link" href = "{% url 'user_logout' %}"> logout </a></li>
      <li><a href="{% url 'base:add'%}">add</a></li>
      <li><div class="dropdown">
      <button onclick="myFunction()" class="dropbtn">Menu</button>
      <div id="myDropdown" class="dropdown-content">
        <a href="{% url 'base:search'%}">Search</a>
        <a href="{% url 'base:show'%}">Show</a>
      </div>
        {% endif %}
        <li><a  href="{% url 'base:home'%}">Home</a></li>

    </div></li>

    </ul>
</ul></div>

<script>
    function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown menu if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>

templates/home.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
      <meta charset="UTF-8">
      <title>Student Affairs Website </title>
      <meta name="description" content="This our Student Affairs website">
      <link rel="stylesheet" href="{% static 'css/mater.css' %}">
</head>
<header>
  <div id="header">
      {% include 'header.html' %}
  </div>
</header>
<body>

  <div class="content">
  <h1>
WELCOME <br>
STUDENTS AFFAIRS SYESTEM</h1>
<h2>FACULTY OF COMPUTERS AND ARTIFICIAL INTELLIGENCE</h2>
</div>
</body>

<footer>
  <dev id="footer">
      {% include 'footer.html' %}

  </dev>

</footer>

</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
  <meta charset="UTF-8">
  <title>Student Affairs Website </title>
  <meta name="description" content="This our Student Affairs website">
  <link rel="stylesheet" href="static/css/index.css">

</head>
<body>
<header>    
    <div id="header">
    <div>
          <ul>
            <li style="float: left;padding: 10px;" id="facultyName"><label>F C A I</label></li>
        </ul>
    </div>
    </div>
</header>
<div class="content">
    <div class="slidershow middle">
        <div class="slides" >
            <input type="radio" name="r" id="r1" checked>
            <input type="radio" name="r" id="r2">
            <input type="radio" name="r" id="r3">
            <input type="radio" name="r" id="r4">
            <div class="slide s1" >
                <p><a href="{% url 'base:home' %}">Student Affairs System</a></p>
            </div>
            <div class="slide" class="s2">
                <p>Human Resources System</p>
            </div>
            <div class="slide" class="s3">
                <p>Higher studies System</p>
            </div>
            <div class="slide" class="s4">
                <p> Laboratory tracking System</p>
            </div>
        </div>
        <div class="navig">
            <label for="r1" class="bar"></label>
            <label for="r2" class="bar"></label>
            <label for="r3" class="bar"></label>
            <label for="r4" class="bar"></label>
        </div>
    </div>


</div>

<div class="footer-basic">

    <footer>
        <ul class="list-inline">
        <li style="float: left;; "><img src = "static/logos/facultyLogo.webp" id="universityLogo"></li>
    <li style="float: left; "><img src = "static/logos/universityLogo.webp"  id="facultyLogo"></li>
        </ul>
        <p class="copyright">Copyright © 2022-2023 Faculty of Computers and Artificial Intelligence 5 Dr. Ahmed Zewail Street, Postal Code: 12613, Orman, Giza, Egypt.</p>
    </footer>
</div>
</body>


</html>